version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building React app..."
      - npm run build
  post_build:
    commands:
      - echo "Deploying to S3 bucket: $S3_BUCKET"
      - aws s3 sync build/ s3://$S3_BUCKET --delete
      - echo "Invalidating CloudFront cache for distribution: $CLOUDFRONT_ID"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: build
