version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building React app..."
      - npm run build

  post_build:
    commands:
      - echo "S3 Bucket: $S3_BUCKET"
      - echo "CloudFront Distribution ID: $CLOUDFRONT_ID"
      - echo "Syncing build output to S3..."
      - aws s3 sync dist/ s3://$S3_BUCKET --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist
