version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing npm dependencies...
      - npm install
  
  pre_build:
    commands:
      - echo Compiling TypeScript...

  build:
    commands:
      - echo "Running Build"
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
