version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing npm dependencies...
      - npm install
  
  pre_build:
    commands:
      - echo Compiling TypeScript...
      - npm run build

  build:
    commands:
      - echo $CLOUDFRONT_ID
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist
