version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building React app..."
      - npm run build

  post_build:
    commands:
      - echo "Deploying to S3 and invalidating CloudFront..."
      - echo "Using S3 bucket: $S3_BUCKET"
      - echo "Using CloudFront Distribution ID: $CLOUDFRONT_ID"
      - aws s3 sync dist/ s3://$S3_BUCKET --delete
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist
